// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNmcooQ6nUxFnhar5gZsFFxfgI-EZxGXc',
    appId: '1:943566929215:web:8de84a824184be0f77678a',
    messagingSenderId: '943566929215',
    projectId: 'pingme-11c08',
    authDomain: 'pingme-11c08.firebaseapp.com',
    storageBucket: 'pingme-11c08.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXAPQ2VZ-zLfXQs0MArpy1xuitRJEoHRg',
    appId: '1:943566929215:android:c9130a0a9cea907a77678a',
    messagingSenderId: '943566929215',
    projectId: 'pingme-11c08',
    storageBucket: 'pingme-11c08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKM5zYIa4fZcj9c_JWlC6w4WaAR6BaXMw',
    appId: '1:943566929215:ios:cdd9ffb141a8efae77678a',
    messagingSenderId: '943566929215',
    projectId: 'pingme-11c08',
    storageBucket: 'pingme-11c08.firebasestorage.app',
    iosBundleId: 'com.example.pingme',
  );
}
